#!/usr/bin/env python3
"""Turns the raw disassembly into an annotated listing.

Inserts the documented names from symbols.py: header comments in front of
known routines, plain text behind RAM addresses, bits, strobes and jump
targets. The listing itself stays unchanged — annotations are only added on
the right, so addresses and bytes remain comparable with the original.

    python3 annotate.py 13     ->  PM5139_V13_annotated.asm
    python3 annotate.py 15     ->  PM5139_V15_annotated.asm

For V1.5, mapv15.py --write has to have run before; it maps the addresses
measured on V1.3 onto V1.5.
"""
import re, sys, textwrap
import symbols

VERSION = sys.argv[1] if len(sys.argv) > 1 else '13'
SOURCE  = f'PM5139_V{VERSION}_disasm.asm'
TARGET  = f'PM5139_V{VERSION}_annotated.asm'

# Measurements were made on V1.3. For V1.5, mapv15.py supplies the shifted
# addresses in symbols_v15.py; RAM, bits and strobes hold for both.
if VERSION == '15':
    try:
        import symbols_v15 as symtab
    except ImportError:
        sys.exit('symbols_v15.py missing - run "python3 mapv15.py --write" first')
else:
    symtab = symbols


line_re  = re.compile(r'^([0-9A-F]{4})  ([0-9A-F ]{2,10})\s+(\S+)\s*(.*?)\s*$')
label_re = re.compile(r'^(L[0-9A-F]{4}:)(.*)$')

def ram_name(a):
    if a in symtab.RAM:
        return symtab.RAM[a][0]
    for lo, hi, txt in symtab.RAM_RANGES:
        if lo <= a <= hi and (hi - lo) > 4:
            return None          # ranges are explained in the header, not per line
    return None

def annotate(mnem, rest, adr):
    """returns a short explanation for the line, or None"""
    parts = []

    # strobe: MOV DPH,#8nh
    m = re.search(r'MOV\s+DPH,#([0-9A-F]{2})h', mnem + ' ' + rest)
    if m:
        v = int(m.group(1), 16)
        if v in symtab.STROBES:
            parts.append(symtab.STROBES[v])

    # I2C address: MOV A,#xxh immediately before an I2C start
    m = re.search(r'MOV\s+A,#([0-9A-F]{2})h', mnem + ' ' + rest)
    if m:
        v = int(m.group(1), 16) & 0xFE
        if v in symtab.I2C:
            parts.append('I2C address ' + symtab.I2C[v])

    # bit addresses such as 2Eh.4
    for b in re.findall(r'/?([0-9A-F]{2}h\.\d)', rest):
        if b in symtab.BITS:
            n, e = symtab.BITS[b]
            parts.append(f'{b} = {n}')

    # jump and call targets
    m = re.search(r'\b(LCALL|ACALL|LJMP|AJMP|JMP)\s+X?([0-9A-F]{4})h', mnem + ' ' + rest)
    if m:
        t = int(m.group(2), 16)
        if t in symtab.ROUTINES:
            parts.append(symtab.ROUTINES[t][0])

    # direct RAM addresses
    if True:
        for a in re.findall(r'(?<![.\w])([0-9A-F]{2})h(?!\.)', rest):
            v = int(a, 16)
            if v >= 0x80:
                continue                      # SFR, already named by the disassembler
            n = ram_name(v)
            if n and n not in ' '.join(parts):
                parts.append(f'{a}h = {n}')

    return '; ' + ', '.join(parts) if parts else None

def header(adr):
    """header comment in front of a known routine"""
    if adr not in symtab.ROUTINES:
        return []
    name, txt, sect = symtab.ROUTINES[adr]
    out = ['', ';' + '-' * 76, f'; {name}']
    for z in textwrap.wrap(txt, 72):
        out.append('; ' + z)
    if sect:
        out.append(f'; see PM5139_Hardware_Reference.md, section {sect}')
    out.append(';' + '-' * 76)
    return out

def main():
    src = open(SOURCE, encoding='utf-8', errors='replace').read().splitlines()
    out = []
    out.append(f'; Philips PM5139 - firmware V{VERSION[0]}.{VERSION[1]} - annotated listing')
    out.append('; Generated by annotate.py from %s and %s.'
               % (SOURCE, 'symbols_v15.py' if VERSION == '15' else 'symbols.py'))
    if VERSION == '15':
        out.append('; The addresses come from mapv15.py, the structural comparison with V1.3.')
        out.append('; Measurements were made on V1.3 - names hold where both versions agree.')
    out.append('; Do not edit by hand - names and texts live in symbols.py.')
    out.append('; Every name is documented: listing, emulator measurement or service manual.')
    out.append(';')
    out.append('; Register convention of the arithmetic library (section 24):')
    out.append(';   X = 10h..14h   Y = 15h..19h   Z = 1Ah..1Eh   W = 30h..34h')
    out.append('; Strobe: MOV DPH,#8nh followed by MOVX @DPTR triggers STRn.')
    out.append(';')
    for lo, hi, txt in symtab.RAM_RANGES:
        out.append(f'; RAM {lo:02X}h..{hi:02X}h  {txt}')
    out.append('')

    hits_header = hits_line = 0
    for z in src:
        m = line_re.match(z)
        if m:
            adr = int(m.group(1), 16)
            h = header(adr)
            if h:
                out.extend(h); hits_header += 1
            a = annotate(m.group(3), m.group(4), adr)
            if a and ';' not in z:
                z = f'{z:<44}{a}'
                hits_line += 1
            out.append(z)
            continue
        # label: put the routine name behind it
        m = label_re.match(z)
        if m:
            adr = int(m.group(1)[1:5], 16)
            if adr in symtab.ROUTINES:
                z = f'{m.group(1)}   ; {symtab.ROUTINES[adr][0]}{m.group(2)}'
        out.append(z)

    open(TARGET, 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    print(f'{TARGET}: {len(out)} lines, {hits_header} routine headers, '
          f'{hits_line} annotated lines')
    missing = [a for a in symtab.ROUTINES if a not in
               {int(line_re.match(z).group(1), 16) for z in src if line_re.match(z)}]
    if missing:
        print('not found in the listing: ' + ' '.join('%04X' % a for a in sorted(missing)))

if __name__ == '__main__':
    main()
