#!/usr/bin/env python3
"""Maps the symbol addresses from V1.3 onto V1.5.

Two methods, in this order:

1. **Structural comparison** as in seqdiff.py: both ROMs are
   disassembled, the instruction sequences reduced to tokens (relative
   jump distances instead of absolute targets) and compared with
   SequenceMatcher. The address mapping falls out of the matching blocks
   directly. This carries even where jump targets have moved.
2. **Signature search** as a fallback for tables and data the
   disassembler does not recognise as code: search for the first bytes
   in V1.5 and accept them only if they occur exactly once.

Anything ambiguous is reported and not adopted — better no symbol than a
wrong one.

    python3 mapv15.py            shows the mapping
    python3 mapv15.py --write    creates symbols_v15.py
"""
import sys, re, difflib
import symbols
import analyze2

_RE = re.compile(r'X[0-9A-F]{4}h')

def _tokens(p):
    """reduce the instruction sequence to comparable tokens (as in seqdiff.py)"""
    S = sorted(p.insn); toks = []
    for a in S:
        l, t, tg, k = p.insn[a][:4]
        if tg is not None:
            d = tg - a
            t = _RE.sub('@%+d' % d if abs(d) < 0x80 else '@ABS', t)
        if t.startswith('MOV   DPTR'):
            t = 'MOV   DPTR,#PTR'
        toks.append(t)
    return S, toks

def structure_map():
    """V1.3 address -> V1.5 address, taken from the matching blocks"""
    A = analyze2.load('13'); B = analyze2.load('15')
    SA, TA = _tokens(A); SB, TB = _tokens(B)
    sm = difflib.SequenceMatcher(None, TA, TB, autojunk=False)
    m = {}
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag != 'equal':
            continue
        for k in range(i2 - i1):
            m[SA[i1+k]] = SB[j1+k]
    return m

R13 = open('M27512_PM5139_V13.bin','rb').read()
R15 = open('M27512_PM5139_V15.bin','rb').read()

def find(sig):
    """all occurrences of a byte sequence in V1.5"""
    hits, a = [], R15.find(sig)
    while a >= 0:
        hits.append(a)
        a = R15.find(sig, a+1)
    return hits

def map_by_signature(adr, minlen=10, maxlen=32):
    """search for the shortest unique signature starting at adr"""
    for n in range(minlen, maxlen+1):
        sig = R13[adr:adr+n]
        if len(sig) < n:
            return None, 'at the end of the ROM'
        t = find(sig)
        if len(t) == 1:
            return t[0], 'signature %d bytes' % n
        if not t:
            return None, 'not found (from %d bytes on)' % n
    t = find(R13[adr:adr+maxlen])
    return None, 'ambiguous, %d occurrences' % len(t)

# Filled in by hand because neither structure nor signature applies:
# in V1.5 the checksum sits at B3CAh (section 17) and the identification
# string with its length byte at B3AEh (section 28).
MANUAL = {0xAC70: 0xB3CA, 0xAC54: 0xB3AE}

def main():
    print('disassembling both versions ...')
    struct = structure_map()
    print('structural comparison: %d instructions matched\n' % len(struct))

    table, unclear = {}, []
    for adr in sorted(symbols.ROUTINES):
        name = symbols.ROUTINES[adr][0]
        if adr in struct:
            table[adr] = (struct[adr], name, 'structure')
            continue
        if adr in MANUAL:
            table[adr] = (MANUAL[adr], name, 'filled in by hand')
            continue
        new, how = map_by_signature(adr)      # fallback for tables and data
        if new is None:
            unclear.append((adr, name, how))
        else:
            table[adr] = (new, name, 'signature: ' + how)

    print('%d of %d symbols mapped unambiguously\n' % (len(table), len(symbols.ROUTINES)))
    print('  V1.3   V1.5   shift         name')
    for a in sorted(table):
        b, name, how = table[a]
        mark = '' if how == 'structure' else '  (' + how + ')'
        print('  %04X   %04X   %+6d       %s%s' % (a, b, b-a, name, mark))
    if unclear:
        print('\nnot adopted:')
        for a, name, how in unclear:
            print('  %04X  %-18s %s' % (a, name, how))

    # Summarise the shifts: this shows how V1.5 is put together
    from collections import Counter
    c = Counter(b-a for a,(b,_,_) in table.items())
    print('\nmost frequent shifts:')
    for d, n in c.most_common(8):
        print('  %+6d  at %d symbols' % (d, n))

    if '--write' in sys.argv:
        with open('symbols_v15.py','w') as f:
            f.write('"""Symbol addresses for V1.5, generated by mapv15.py.\n\n'
                    'Do not maintain by hand: names and texts live in symbols.py,\n'
                    'the addresses come from a signature search in the V1.5 ROM.\n"""\n')
            f.write('ROUTINES = {\n')
            for a in sorted(table):
                b, name, how = table[a]
                txt, sect = symbols.ROUTINES[a][1], symbols.ROUTINES[a][2]
                f.write('    0x%04X: (%r, %r, %r),   # V1.3 %04X\n' % (b, name, txt, sect, a))
            f.write('}\n')
            # RAM, bits and strobes are version independent
            f.write('from symbols import RAM, RAM_RANGES, BITS, STROBES, I2C\n')
        print('\nsymbols_v15.py written: %d routines' % len(table))

if __name__ == '__main__':
    main()
