"""Symbol addresses for V1.5, generated by mapv15.py.

Do not maintain by hand: names and texts live in symbols.py,
the addresses come from a signature search in the V1.5 ROM.
"""
ROUTINES = {
    0x0006: ('MAIN_LOOP', 'main loop entry, clears accumulator and PSW', None),   # V1.3 0006
    0x04BE: ('KEY_DECODER', 'decodes the SAA3007 word from P3.3', 11),   # V1.3 0227
    0x07CA: ('PARAM_CHECK', 'handler: loads the parameter, fetches the flag byte from 069Dh, and on bit 7 or 6 checks the limit through 1121h', 33),   # V1.3 0663
    0x0805: ('TAB_PARAM_FLAGS', 'flag byte per parameter index; bit 7 or 6 means limit-checked', 33),   # V1.3 069D
    0x045E: ('PARAM_ADDRESS', 'R0 = RAM address of the selected parameter from table 08F2h, index 24h & 0Fh; R2 = decade', 33),   # V1.3 08EA
    0x0A18: ('OUT_DC_AMPL', 'fixed setting to STR7 and STR9', 22),   # V1.3 09AF
    0x0A28: ('OUT_FREQ', 'computes the frequency and sends it to the TWS', 18),   # V1.3 09BF
    0x0A4E: ('FREQ_EXPONENT', 'ORs the decade index from table 09EAh into 12h', 18),   # V1.3 09E5
    0x0A8F: ('FREQ_BCD2BIN', 'frequency 50h..52h from BCD to binary, 24 bit', 18),   # V1.3 0A26
    0x0AF9: ('OFFSET_CALC', 'computes the DC component', 22),   # V1.3 0A90
    0x0BBA: ('AMPL_CALC', 'computes the amplitude', 20),   # V1.3 0AAC
    0x0BE4: ('AMPL_CORRECT', 'amplitude correction per waveform', 20),   # V1.3 0B57
    0x0EDB: ('SEND_STR6', 'four bytes from 11h..14h to the TWS, unit 2 D331', 4),   # V1.3 0E54
    0x0EE2: ('SEND_STR7', 'two bytes to the DC generator, unit 3 D301', 4),   # V1.3 0E5B
    0x0EE9: ('SEND_STR9', 'one byte to the amplitude controller, unit 3', 4),   # V1.3 0E62
    0x0EF0: ('SEND_STR5', 'to the modulation oscillator, unit 4: six bytes 14h,13h,12h,11h,19h,18h. Chain SD1 -> D139 -> D138 -> D130. 11h..14h = TWS frequency word, 19h = DAC N135, 18h = multiplexer D140/D141', 30),   # V1.3 0E69
    0x0EFF: ('SEND_STR3', 'to the amplitude modulator and pulse generator, unit 4', 4),   # V1.3 0E78
    0x0F06: ('SEND_STR4', 'to the burst logic, unit 4', 4),   # V1.3 0E7F
    0x0F11: ('SEND_BYTES', 'sends R4 bytes from RAM at R0 downwards through SBUF', 3),   # V1.3 0E8A
    0x0F1F: ('STROBE_FIRE', 'ORs DPH with 80h, MOVX, then returns to the idle output', 3),   # V1.3 0E98
    0x0FE7: ('MOD_CTRL_BYTE', 'builds 18h from the operating mode: one-hot 2Ch -> bit number, +8 if 2Fh.5 or 2Fh.4, table at 0F83h; bit 1 from 29h.7 AND 2Ch.2. Goes to D139 as the sixth STR5 byte', 30),   # V1.3 0F69
    0x10B0: ('BITS_REVERSE', 'reverses the bit order in the accumulator, ACC.0 against ACC.7 and so on; prepares data for the shift registers, then STR9', 4),   # V1.3 1032
    0x134F: ('TAB_PARAM_LIMITS', '12 upper limits as BCD, indexed by parameter: 2001 201 21 11 11 11 21 101 201 19 10 101. In V1.5 at 134Fh', 33),   # V1.3 12D2
    0x152F: ('SWEEP_SETUP', 'prepares the sweep: time, limits, direction, step sizes', 23),   # V1.3 14B2
    0x1679: ('NORMALIZE', 'shifts Y so that 15h lies in 08h..0Fh; R7 = exponent', 24),   # V1.3 15FC
    0x16A9: ('SWEEP_F_BCD2BIN', 'fSTART or fSTOP to binary, unit 0.1 Hz. 22h.4 selects between them. Truncates the mantissa to 16 bit', 23),   # V1.3 162C
    0x1984: ('SWEEP_START', 'clears the accumulators and step counter, starts timer 1', 23),   # V1.3 1907
    0x19AF: ('SWEEP_LOOP', 'one sweep step: count, ramp, frequency, output', 23),   # V1.3 1932
    0x1D48: ('TWS_SEND', 'four bytes from 14h downwards to the TWS', 23),   # V1.3 1CBA
    0x1D67: ('SWEEP_STEP', 'telegrams of the step, then waits for timer 1', 23),   # V1.3 1CD9
    0x1DC6: ('MANTISSA_X2', 'shifts 11h..14h left by one bit: N = 2*M of the TWS', 18),   # V1.3 1D38
    0x1DDC: ('SWEEP_ROUND', 'adds the rounding carry from R6.7 onto 12h..14h', 23),   # V1.3 1D4E
    0x1DF0: ('RAM_PAGE', 'builds F0h/F1h for STR1, page select of the waveform RAM', 23),   # V1.3 1D62
    0x1E1C: ('SWEEP_RESCALE', 'rescales the accumulator, table 2019h, then adds fSTART', 23),   # V1.3 1D8E
    0x1EEA: ('SWEEP_LOG_EXP', 'logarithmic branch: exponent and fractional part', 23),   # V1.3 1E5C
    0x1FCE: ('BIT_SHIFT', 'shifts Y by R5 bits, encoding see section 23', 23),   # V1.3 1F40
    0x20A7: ('TAB_RESCALE', '40 shift codes, index 25h minus 1Fh', 23),   # V1.3 2019
    0x20CF: ('TWS_DECADE', 'determines the decade of the TWS word, result in R7', 23),   # V1.3 2041
    0x21E5: ('TAB_ACCESS_2200', 'helper for the table access at 2200h in the arithmetic library; computes in X', 24),   # V1.3 2157
    0x22A6: ('POWER_OF_TWO', 'X = W * 2^((13h+14h/256)/256) * 65536; table 2398h, linearly interpolated', 23),   # V1.3 2218
    0x23B1: ('LOGARITHM', 'searches table 2398h backwards: index and remainder = logarithm', 23),   # V1.3 2323
    0x2426: ('TAB_POW2', '257 entries: round((2^(i/256)-1)*65536), for exp and log', 23),   # V1.3 2398
    0x2650: ('KNOB_QUADRATURE', 'counts detents; F0 holds the direction of rotation', 19),   # V1.3 25C2
    0x2684: ('KNOB_EVALUATE', 'turns the detent count into a step size', 21),   # V1.3 25F6
    0x269C: ('TAB_ACCEL2', 'acceleration from 16 detents on', 21),   # V1.3 260E
    0x26B0: ('TAB_ACCEL', 'acceleration, up to 15 detents', 21),   # V1.3 2622
    0x275A: ('TAB_WEIGHTS', 'weight per digit position', 19),   # V1.3 26AB
    0x27D3: ('TAB_INCREMENT', '32 BCD increments, geometric from 1 to 5000', 19),   # V1.3 2724
    0x2813: ('INCREMENT_ADD', 'adds increment 1Ch..1Eh onto 17h..19h; F0=0 adds, F0=1 subtracts', 19),   # V1.3 2764
    0x2888: ('TRIAL_SUBTRACT', 'subtraction on trial first; 22h.6 = zero, 22h.7 = underflow', 19),   # V1.3 27D9
    0x2A78: ('RANGE_CHECK', 'range check, jump table 29DBh by parameter', 19),   # V1.3 29C9
    0x2AC5: ('FREQ_RANGE', 'frequency limits; table 2A81h, clamps at 0Bh=11h to 20000', 19),   # V1.3 2A16
    0x2B3A: ('TAB_FREQ_LIMITS', 'limit per decade, stored halved', 19),   # V1.3 2A81
    0x2F45: ('NVRAM_MARK', 'check mark of a memory record: byte sum from RAM 30h with start value AAh over 25 bytes, over 24 when an arbitrary curve is selected', 26),   # V1.3 2EA1
    0x2FEF: ('NVRAM_ADDR_READ', 'device address from NVRAM FEh/FFh; the mark is value+55h, checked by XOR, otherwise default 20h', 26),   # V1.3 2F51
    0x303F: ('MUL_XYZ', 'X = Y * Z, 40 bit without loss', 24),   # V1.3 2FA0
    0x30C8: ('X_TIMES_BYTE', 'multiplies X by the byte in R6, carry into R3', 24),   # V1.3 3029
    0x31A6: ('DIV_XYZ', 'X = Y / Z, integer, rounded down', 24),   # V1.3 3107
    0x3266: ('COMPARE_YZ', 'compares Y against Z', 24),   # V1.3 31C7
    0x3276: ('COMPARE_5', 'five bytes @R0 minus @R1, result in the carry', 24),   # V1.3 31D7
    0x3283: ('CLEAR_XYZ', 'clears X, Y and Z, 15 bytes from 10h', 24),   # V1.3 31E4
    0x328D: ('CLEAR_X', 'clears X', 24),   # V1.3 31EE
    0x3291: ('CLEAR_Y', 'clears Y', 24),   # V1.3 31F2
    0x3295: ('CLEAR_Z', 'clears Z', 24),   # V1.3 31F6
    0x32A1: ('X_TO_Z', 'moves X to Z, clearing the source', 24),   # V1.3 3202
    0x32A5: ('X_TO_Y', 'moves X to Y, clearing the source', 24),   # V1.3 3206
    0x32D5: ('Y_RIGHT', 'shifts Y right by one bit', 24),   # V1.3 3236
    0x32ED: ('X_LEFT', 'shifts X left by one bit', 24),   # V1.3 324E
    0x32F1: ('Y_LEFT', 'shifts Y left by one bit', 24),   # V1.3 3252
    0x32F5: ('Z_LEFT', 'shifts Z left by one bit', 24),   # V1.3 3256
    0x330A: ('NIBBLE_LEFT', 'shifts five bytes left by one nibble, BCD times ten', 24),   # V1.3 326B
    0x334D: ('Y_MINUS_Z_ABS', 'Y = |Y - Z|; carry set if Z was larger', 24),   # V1.3 32AE
    0x337A: ('BIN2BCD', 'binary to BCD, digits accumulated in 14h', 24),   # V1.3 32DB
    0x33B2: ('BCD2BIN', 'six BCD digits from 17h..19h to binary in 12h..14h', 24),   # V1.3 3313
    0x33D7: ('BIT_LENGTH', 'bit length of a five-byte value into R4', 24),   # V1.3 3338
    0x3420: ('DISPLAY_BUILD', 'builds the display buffer 30h..43h from the device state', 15),   # V1.3 3381
    0x38AE: ('DISPLAY_SEND', 'sends the display buffer over I2C to the PCF8576 (70h)', 14),   # V1.3 37DB
    0x3A02: ('DISPLAY_SEND2', 'second path to the display', 14),   # V1.3 392F
    0x3B70: ('RESET', 'reset entry point', 1),   # V1.3 3A9A
    0x3EB2: ('LOAD_SINE', 'waveform table 44A7h into the waveform RAM through STR2', 6),   # V1.3 3DAB
    0x4003: ('LOAD_HAVERSINE', 'waveform table 46A9h into the waveform RAM, 512 x 12 bit', 6),   # V1.3 3EFC
    0x4513: ('LOAD_LEVEL_SERIES', 'waveform table 4AABh into the waveform RAM: ten sine arcs with logarithmically falling amplitude, 3.33 dB per step', 6),   # V1.3 4425
    0x4FAC: ('POINTER_CHECK', 'checks which parameter the digit pointer 0Bh selects; five entry points from the user interface', 21),   # V1.3 4EBE
    0x526B: ('STATUS_READ', 'reads the status register through STR0', 5),   # V1.3 517D
    0x5275: ('I2C_START_W', 'start condition, address in A with R/W=0', 28),   # V1.3 5187
    0x5282: ('I2C_START_R', 'start condition, address in A with R/W=1', 28),   # V1.3 5194
    0x528F: ('I2C_BYTE', 'sends one byte, MSB first; ACK ends up in the carry', 28),   # V1.3 51A1
    0x52AF: ('I2C_STOP', 'stop condition', 28),   # V1.3 51C1
    0x5B45: ('TEST_MENU', 'menu of the diagnostic program; jump table 5A0Bh', 7),   # V1.3 59D1
    0x5B7F: ('TAB_SELFTEST', 'eight LJMP entries pointing at the test programs', 7),   # V1.3 5A0B
    0x5BA3: ('TEST1_DISPLAY', 'self-test 1: Display Test', 7),   # V1.3 5A2F
    0x5BB6: ('TEST2_KEYBOARD', 'self-test 2: Keyboard Test', 7),   # V1.3 5A42
    0x5C4F: ('TEST3_MEMORY', 'self-test 3: Memory Register Test', 7),   # V1.3 5ADB
    0x5CB8: ('TEST4_STROBE', 'self-test 4: Strobe Test', 7),   # V1.3 5B44
    0x5D7F: ('TEST5_IFACE', 'self-test 5: Interface Test, RS-232 or IEEE-488', 7),   # V1.3 5C0B
    0x5F10: ('TEST6_KNOB', 'self-test 6: Rotary Knob Test', 7),   # V1.3 5D68
    0x609B: ('TEST7_EEPROM', 'self-test 7: EEPROM Test', 7),   # V1.3 5EE9
    0x6111: ('IFACE_SEARCH', 'searches for the card; an ACK sets 25h.7', 28),   # V1.3 5F74
    0x6163: ('IFACE_RECEIVE', 'reads the status byte, the data block and the checksum', 28),   # V1.3 5FA9
    0x6302: ('IFACE_LOCREM', 'control byte E2h = LOCAL, E3h = REMOTE; sets 26h.1', 28),   # V1.3 6130
    0x631F: ('IFACE_START_W', 'checks the bus, then start at 5Eh for writing', 28),   # V1.3 614A
    0x632D: ('IFACE_START_R', 'checks the bus, then start at 5Eh for reading', 28),   # V1.3 6158
    0x6416: ('IFACE_BYTE_STOP', 'sends a byte, then stop', 28),   # V1.3 6244
    0x642C: ('I2C_RELEASE', 'releases the bus and sends stop', 28),   # V1.3 625A
    0x6650: ('ERROR_REPORT', 'A = error number: stored in 49h, class mask from table 6465h (56 bytes) ORed into 69h, 24h.3 set', 32),   # V1.3 645A
    0x6693: ('ERROR_SELECT', 'picks the error number matching the operating mode and reports it through 64BBh to ERROR_REPORT', 32),   # V1.3 649D
    0x6865: ('REMOTE_SWITCH', 'checks the status register and sets or clears 2Eh.3', 28),   # V1.3 666A
    0x6C6F: ('CMD_DISPATCH', 'command code in 10h: upper nibble 60h -> 8871h, C0h -> 6B51h, otherwise the shared interpreter 71BFh', 32),   # V1.3 6A85
    0x6D78: ('CMD_C0', 'execution part of command group C0h: the IEEE-488.2 common commands *CLS *ESE *ESR *OPC *RST *SRE *STB *TST *WAI', 32),   # V1.3 6B51
    0x6F6C: ('TAB_LRN', '50 bytes: which command tokens describe the setting per operating mode, eight groups separated by 00h, ordered like the one-hot byte 2Ch. Basis of the learn query *LRN?', 32),   # V1.3 6CEC
    0x6F9E: ('REPLY_BUILD', 'assembles the remote control reply texts in the buffer at 4Fh; uses MSG_APPEND and table 6CECh', 32),   # V1.3 6D1E
    0x746A: ('CMD_INTERPRET', 'shared command interpreter for keyboard and remote control, table 7752h', 16),   # V1.3 71BF
    0x76B7: ('ARG_PARSE', 'parses the argument of a command, called from 6B51h (group C0h) and 71C7h; carry signals failure', 32),   # V1.3 7415
    0x79E5: ('TAB_COMMANDS', '131 entries of 16 bytes: 14 bytes name, then token with parameter and token alone. See PM5139_Tables.md', 16),   # V1.3 7752
    0x8327: ('MSG_APPEND', 'appends the message with index R4 from pointer table 803Ch to the buffer at 4Fh', 16),   # V1.3 8014
    0x8B97: ('CMD_60', 'entry of command group 60h from dispatcher 6A91h: the arbitrary commands ARB ARBSELECT ARBITEXECUTE ARON AROFF CLARB BEGIN COUNT DATA FILL. Largest contiguous block of the ROM', 32),   # V1.3 8871
    0x8D3E: ('ARB_PART_8A1C', 'second large execution part of group 60h, from 6804h and three places inside the block; computes in Z and Y, reports errors through 645Ah', 32),   # V1.3 8A1C
    0x8FEB: ('ARB_PART_8CB9', 'from 63FDh; stores 34h/35h in the upper RAM buffer at FBh..FDh and works with 4Bh/4Ch, the interface pointers', 32),   # V1.3 8CB9
    0x914A: ('ARB_HELPER_8DE3', 'short helper without calls of its own, from 6B4Dh and five places inside the block', 32),   # V1.3 8DE3
    0x9183: ('ARB_HELPER_8E1C', '22 bytes, from 6EC5h; calls 8E11h and 8DE3h', 32),   # V1.3 8E1C
    0x9199: ('ARB_HELPER_8E32', '35 bytes, from 3CEDh in the initialisation', 32),   # V1.3 8E32
    0x91BC: ('ARB_PART_8E55', 'from 6896h; display cells 32h/33h/3Eh, reads the status register', 32),   # V1.3 8E55
    0x926A: ('ARB_PART_8F03', 'largest sub-area, from 68A2h and four places inside the block; builds the display, reads the status register, uses the interface pointer 4Ch', 32),   # V1.3 8F03
    0x974D: ('ARB_DIR_CHECK', 'checks the arbitrary EEPROM directory: header 0000h = count in the lower nibble, 0001h = check byte over n*5+5 bytes from 0002h, start value 55h + header byte. On failure 22h.7', 32),   # V1.3 9615
    0x990B: ('ARB_OUTPUT', 'output sequence with fixed constants through 43ADh and 10B5h, from 3B74h, 3D08h and four places inside the block', 32),   # V1.3 97D9
    0x99E4: ('ARB_PART_98B3', 'from 5F01h and 966Bh; sets Y to 0200h and masks, uses the curve number 67h', 32),   # V1.3 98B3
    0xAE2B: ('LOAD_ARB_ROM', 'one of the three built-in curves A047h/A447h/A847h, selected through RAM 0Dh', 6),   # V1.3 9E37
    0xB3A1: ('VERSION_DISPLAY', 'shows the firmware version at power-up: 3Fh = first cell with separator, 40h = second, then DISPLAY_SEND. V1.3 sets 0Eh/3Dh = "1.3", V1.5 0Eh/B5h = "1.5". Runs inside the reset sequence at 3AA8h', 34),   # V1.3 AC47
    0xB3AE: ('IDENT_STRING', 'length byte 1Ah, then PHILIPS,PM5139,0,V1.3/0000', 28),   # V1.3 AC54
    0xB3CA: ('ROM_CHECKSUM', 'checksum of the ROM', 1),   # V1.3 AC70
}
from symbols import RAM, RAM_RANGES, BITS, STROBES, I2C
